### ISSUE TITLE
Feature request: Dehaze and buttons

### ISSUE THREAD

**Issue by lewiswalsh** [thegouger/MIDI2LR#1]
This is great! It works flawlessly with my Korg nanokontrol2.

It would be great to have access to the dehaze slider. And also to assign buttons to discrete operations such as 'flag as picked' and 'reject'

**Comment by thegouger** [comment]
Added Dehaze here: d1c452565754437402185686d9b203cb03deb16c

Button actions are currently a work in progress (I'll make a new release when it's done)

**Comment by thegouger** [comment]
Buttons and Dehaze are available in the latest release
https://github.com/thegouger/MIDI2LR/releases/tag/v0.2
