### ISSUE TITLE
"Tools" bug...

### ISSUE THREAD

**Issue by Flowersoft** [thegouger/MIDI2LR#11]
When set "Tools" with keyboard or mouse, the "PREW_TOOL" variable contain bad value. Perhaps the "LrDevelopController.getSelectedTool()" function should be used...

LrDevelopController.getSelectedTool()
Reports which tool mode is active in Develop. Must be called while the Develop module is active.
First supported in version 6.0 of the Lightroom SDK.

Return value
(string) current tool mode, one of: "loupe", "crop", "dust", "redeye", "gradient", "circularGradient", "localized".

**Comment by thegouger** [comment]
Good catch - I'll fix this

**Comment by thegouger** [comment]
Fixed here: 30911676c9d8edf8c07146edfab3f7f7eff08345

**Comment by Flowersoft** [comment]
Thanks!
