### ISSUE TITLE
Hidden Tool Alias!!!!

### ISSUE THREAD

**Issue by Flowersoft** [thegouger/MIDI2LR#14]
Heureka!
I'm find a not documented  LrDevelopController.SelectTool() function variable named 'white_balance'.  It is equal to key-function (W) activate  the white balance selection tool...

Please, add this function to the Tool-section, if it is possible.

**Comment by Flowersoft** [comment]
I'm sad...

As I see it, the 'white_balance' is able only to read. GetSelectedTool() is working when LR is in "White Balance Selector" mode, and return with 'white_balance' value, however the SelectTool('white_balance') is unusable.  B-(

You can also try this ...

**Comment by thegouger** [comment]
Yea, trying to select that tool doesn't seem to work unfortunately

**Comment by thegouger** [comment]
Closing this for now as it's not supported in the API. Hopefully one day the LR team adds it :stuck_out_tongue:

**Comment by marcocucinato** [comment]
Hello @thegouger , have you asked it in the feedback.photoshop.com site?
If you want I can also ask this in our internal forum, but I need more specs.
