### ISSUE TITLE
MIDI2LR AutoRun

### ISSUE THREAD

**Issue by Flowersoft** [thegouger/MIDI2LR#15]
The plugin could willl automatically launch the application...

LrTasks.startAsyncTask( function()
	LrShell.openFilesInApp({"/A/default.xml"},"/A/MIDI2LR.exe")
        ...
       ....

One question remains: Determination of the path ...    B-)

**Comment by StefanKellerAC** [comment]
path =  _PLUGIN.path

**Comment by Flowersoft** [comment]
Yes, thanks!

It should be placed on each component (exe, xml, etc.) of the plugin-directory, and LR (plugin) starts the aplication.

local LrShell  = import 'LrShell'
...
...
LrTasks.startAsyncTask( function()
LrShell.openFilesInApp({_PLUGIN.path.."/default.xml"},_PLUGIN.path.."/MIDI2LR.exe")
...
...

**Comment by thegouger** [comment]
Nice, I'll look into doing this

**Comment by Flowersoft** [comment]
Startup may be loaded with a default profile.  e.g.: default.xml

**Comment by Flowersoft** [comment]
Nice!

When I copy the new compiled exe (3f0e479) and default.xml to plugin dir,  and I use autorun (LrShell.OpenFilesinApp), program load the file.

**Comment by thegouger** [comment]
Added here: 6c4f87dbff2c27ae755c4b3fd23c639af4811503

**Comment by Flowersoft** [comment]
Nice!!!!
