### ISSUE TITLE
For endless rotary knobs - improvement

### ISSUE THREAD

**Issue by dusipuffi** [thegouger/MIDI2LR#17]
Great job!
It would be possible if the develop parameters change by mouse or skip other photo, to send to midi current values of parameters? For controllers with endless rotary knobs would be perfect. Now i must first locate "correct" position, and then it works. I have Arturia Beatstep.

**Comment by thegouger** [comment]
I was considering a couple ways of doing this, but actually sending the MIDI values to the controller might be a good way of doing it (I'll have to see just how many can set their internal controller value in this manner).

The other way I was thinking was by having the endless knobs increment/decrement parameters. So turning the knob clockwise would increment the parameters, and when the controller value reaches 127, it will continue incrementing as it receives 127 over and over again (which is how I assume these knobs work).

**Comment by thegouger** [comment]
*In theory* it should work now that b94f5128622806794e03fee11a5ee6003b1b7c17 adds support for sending the controller values on photo change/param updating. This is also present in the latest release.

Whether this *actually* works might depend on the specific MIDI controller.

**Comment by dusipuffi** [comment]
I'm sorry, but for me (midi Arturia Beatstep) it does not work

**Comment by thegouger** [comment]
Ah, looking at the documentation for the Arturia Beatstep, it doesn't seem to set the controller value if you send it MIDI CC messages. However, it appears to be able to output in relative mode - so that's something I will have to support in the application
