### ISSUE TITLE
Toggle pickup check

### ISSUE THREAD

**Issue by marcocucinato** [thegouger/MIDI2LR#18]
Hi,

It would be nice if the pickup check could be disabled in order to immediately set the cursor value.
It could be a global toggle or a line-by-line.
this could also solve issue #17 .

**Comment by thegouger** [comment]
Yup, I'm planning on adding this. The other advantage of this is that it works better for interfaces like TouchOSC and MIDI on touchscreen devices.

**Comment by thegouger** [comment]
Added this here:
00f9df9a003ac031d7b2dc22527434f8e3c879f4
