### ISSUE TITLE
Feature request: Multiple functions per slider OR switchable settings

### ISSUE THREAD

**Issue by retep-m** [thegouger/MIDI2LR#2]
This is a great project! Just got a KORG nano to test this.
The "nano KONTROL2" has lots of Buttons left, and 8 sliders+8potis are not that much to manage Lightroom. 
It would be nice, if one slider could have multiple functions if used with extra buttons.
For example slider 1-8 (CC0-CC7) for "Basic" settings; slider 1 plus the "s" next to it (CC32) for "Tone Curve..." etc.

OR

Pressing CC32 loads settings "Basic.xml", pressing CC33 automatically loads "ToneCurve.xml" etc.

**Comment by edm81363** [comment]
I see what you're thinking here. I have assigned Fader 1 to Exposure, and Knob 1 to Contrast, so that expands the usefulness.

The mapping to load presets is an interesting idea, but something I would put lower on the feature list for my needs.

**Comment by PhoenixTT** [comment]
The Mac-Software Pfixer.LR uses four modes to enlarge the possibilities with the BCF 2000. I work around by sending the CC messages over different midi channels through presets. But perhaps it is possible to do it by using buttons instead of presets.

http://www.pusherlabs.com/media/images/documentation/map-bcf2000.jpg

**Comment by PhantomLordM** [comment]
@retep-m it's great idea, especially for smaller devices like Korg Nanokontrol (which I bought because of MIDI2LR).

**Comment by thegouger** [comment]
Added support for multiple profiles here: 09fbfd2c381aa582910770ac1f7882698f2528be which is available in the latest release. You can now switch through the profiles in a settable profile directory using buttons.

I will continue to make this a bit more user friendly though.
