### ISSUE TITLE
Fader position on photo change

### ISSUE THREAD

**Issue by moutew** [thegouger/MIDI2LR#22]
Hi and first of all thanks a lot for this nice piece of software ! For the time I did'nt earn lot of time with it, but my developpement are far better in that same time !

One of the annoying thing is that on each loading of a photo we have to put the fader at the position where the value is in LR to begin. IE if my picture is at Exposure +1, if I want to be able to adjust the setting with my Berhinger ( old Paddy for LR fan ), I have to reset the fader to this value, and the correct my exposure. I don't know if the MIDI framework allows easily to put control at a certain state. But it was acheive by ... Paddy ;)

**Comment by thegouger** [comment]
I've started looking into this - seems like all I'll have to do is actually send the controller values appropriate to each CC. I hope to implement this soon.

**Comment by PhoenixTT** [comment]
Hello,

do you know how long do you need for this "hope to implement this"?
I am also a big fan of this "paddy" function and bought me the BCF 2000 only for this reason.

I don't want to make pressure but want to decide whether I should start an own fork of you excellent piece of code.

Kind regards
Viktor

**Comment by moutew** [comment]
No need to make a clone I think you can make push requests !
I don't know either C++ or LUA but python. So i can't help, but this little ( for now I hope ) project is awesome !!

**Comment by clearminds** [comment]
If this goes into the stable bransch I am so getting a BCF2000 :)

**Comment by thegouger** [comment]
@PhoenixTT it shouldn't take more than a few days I think (just I won't actually be able to test it)

**Comment by clearminds** [comment]
@thegouger : if you need anyone to test development builds I will have a BCF 2000 arriving this week.

**Comment by thegouger** [comment]
This should *theoretically* be supported now, but I haven't personally tested it.

v0.3.0 adds the functionality where the plugin will send any param updates (when switching photos, using mouse/keyboard to change params) to MIDI2LR, which will then issue the corresponding CC messages.

**Comment by moutew** [comment]
It works really well !!! on a beringher bcf 2000 !
Really really cooooool to use !!

**Comment by PhoenixTT** [comment]
I love the sound of moving faders in the morning ;-)

Thanks a lot, it works like a charm on the BCF 2000.

**Comment by Ruprect** [comment]
GREAT!!! I will test this using TouchOSC for my iPAD and will update here with my discoveries.

**Comment by rubin110** [comment]
Thank you so much for implementing this.

First off is there any why I can donate to your project?

Secondly I have a pair of bugs related to this and am wondering if you'd like me to open separate issues or keep them here?

One bug is that when moving the sliders on my BCF2000 too fast, I notice that Lightroom doesn't pick up on the change. This eventually leads into the next bug.

On occasion the mixer will try to re-position the slider to a previous position as I'm trying to move it.

Thanks again!

**Comment by thegouger** [comment]
I may add a donation link on the site (it would be nice to purchase a BCF2000 so I can actually test with it :stuck_out_tongue: )

In the latest release, I have added an option to disable the pickup mode (which I think should prevent the issue when moving sliders too fast). This should also hopefully resolve the secondary issue.

Let me know if it improves the behaviour.

**Comment by alexlinno** [comment]
Hi
I'm using 0.3.1. with a BCF2000, I'm not gettign an update from CC to the slider....It seems to work for other people so I must be doing something wrong...any hints. Input from BCF2000 to CC works fine

**Comment by thegouger** [comment]
@alexlinno there's a few things you could check:
1. Make sure the plugin version is also 0.3.1 (which you can check by going to File>Plug-in Manager)
2. Make sure no other application is using the MIDI out ports of the BCF2000

I'm not sure about specifically setting up the BCF2000 as I don't own one, but I'll look into seeing whether there's any specific setup required.

**Comment by alexlinno** [comment]
It worked with Paddy for LR but I also programmed the BCF2000 it self a long time ago. I have to remember what that actually did

**Comment by alexlinno** [comment]
don't ask me why but it seems to work now

**Comment by alexlinno** [comment]
ok some more info: it seems that depending many values are different between to photos whether all fader move. I think there needs to be  delay between each fader. for example when all 8 faders have a value of 0 for 1 image and 100 for the next only my first 3 faders move (temp, exp and high). When these values are the same for 2 images the next value faders move correctly.
So I see that is difficult to solve without owning a BCF2000....

**Comment by thegouger** [comment]
Hmm interesting.
I have built a custom MIDI device that I'm going to code to receive MIDI input as well, so maybe it will shed some light on this issue.

**Comment by rubin110** [comment]
There are a couple of BCF2000s on ebay for around $160 to $170 USD. I'm happy to throw $50 into the donation hat to help the developer buy this mixer if others are also willing to do something similar in order to help aid development of MIDI2LR for this hardware. :)

**Comment by alexlinno** [comment]
An improvement on the slider movement of the BCF2000 would be to send an update to the slider only 20msec(or so maybe configurable) after the last update for a specific channel. I.e. not send a a sequence with updates but only the last one for a specific slider/MIDI channel

**Comment by thegouger** [comment]
Cool - I'll add in a slower (and configurable) update rate and we can see if this resolves the issue.

**Comment by alexlinno** [comment]
that would be cool.. this really going to be good. Not only slower update but when a slider in LR is going 11,12,13....20,21 it best to send only 21 (ie wait x msec to see whether it really is the last value). This will cause the sliders to move smoother
And yeah when it comes to adjusting many sliders between 2 images (each slider has only 1 value) there should also be some delay.
BTW I like your home page, cool projects!

**Comment by clearminds** [comment]
One thing that I noticed now when I got my Behringer is that the check that checks how close it is to the old value or not messes up sometimes and makes the slider non responsive. So a feature to turn of the check for motorized MIDI-controllers would be nice

**Comment by thegouger** [comment]
@clearminds the latest release has an option to turn off the 'pickup' mode

**Comment by clearminds** [comment]
Just tried that mode and it works perfect - I do have problems with getting buttons to work though - anyone else that experience the same issue? I have set up the following but they don't get transferred over to LR.
![Settings](https://dl.dropboxusercontent.com/u/15136830/8110cdb5f27d4d627389de2e08a5e4d7.png)

**Comment by thegouger** [comment]
@clearminds So long as the buttons send a value of 127 (if they're CCs) or Note On, it should work. (You should see this in the top right hand corner indicating the last MIDI command).

One thing to note is on the BCF2000, the buttons work in a toggle mode (ie press it once turns it 'On', pressing again turns it 'Off') meaning you'd have to press it twice in order to do an action.
I will add a setting to the settings page to allow either On/Off to execute actions.

**Comment by clearminds** [comment]
Mine sends just 1 - and they don't toggle - it sends 1 and then it goes back to 0

**Comment by thegouger** [comment]
@clearminds ok, I'll add a fix for this. Heh, all these MIDI controllers do things slightly differently :stuck_out_tongue:

**Comment by clearminds** [comment]
Thank you! And add that donation link! :)

**Comment by thegouger** [comment]
@alexlinno I made a test build with the settable update rate [Download](https://github.com/thegouger/MIDI2LR/releases/tag/v0.3.2-fader-update-test). 

Right now it defaults to 20ms, but is settable up to 50ms. Note that if you change this value, MIDI2LR will have to be restarted for it to take effect.

Let me know if that resolves the multiple faders not updating issue.

**Comment by alexlinno** [comment]
Hi, first of all it would be very helpful if somebody else with a BCF2000 could confirm the behaviour I see. As said it works fine with PAddy but of course there could be something with my setup
It didn't help at all. But I think I found another pattern...when switching between to images always only 2 faders change value and it are the ones that are different and from the top down. Say one image has exp:100,white:100 and another one contrast:100, the rest is zero. Than when switching from the second to the first will change change the exp from 0 to 100, contrast from 100 to 0, but the whites don't change. and vice versa the white will stay at 100. 
When then setting the contrast for image 2 to 0: then switching changes exp and white since that are the only 2 values that different. I also tried other values that are the same but not 0.0 and the effect is the same. Tome it seems that LR doesn't send any thing when the values are the same and that only 2 values make it ti the BCF.
Another note is that my faders are not in the same order on the BCF (left to right)as they are in LR(top to bottom)

I have your code so I can debug a bit this weekend although I have some other projects running, so I cannot promise anything

**Comment by alexlinno** [comment]
I assume MIDISender::sendCC is sending to MIDI device? Or is it sending to LR CC? If the latter just forget all text below which is just an indication that 4 sliders moved. But from debugging it seems that  MIDISender::sendCC is sending to MIDI
Funny thing is when I break in your  MIDISender::sendCC it breaks only 3 times whilst 8 faders need to be changed.LR_IPC_IN::processLine(String& line) is also called  only 4 times (of which 3 fader values,tint is coming from LR but I have no slider assigned to it yet). In  LR_IPC_IN::run() it also reaches the if (canReadLine) only 4 times (temp,tint,exp,high).
LR_IPC_IN::run() is only called 4 times.
Might there be a socket/buffer throwing away stuff from LR to MIDI2LR.....anyways will debug a bit more later

**Comment by alexlinno** [comment]
Sorry I didn't mean LR_IPC_IN::run() is called 4 times but the while (!threadShouldExit())loop is run 4 times before  waitUntilReady(true, 0) returns 0 als the time; Until the next switch. So it is somewhere i nthe Juce_Socket waitForReadiness something goes wrong

**Comment by thegouger** [comment]
Ah, interesting, I'll debug this

**Comment by thegouger** [comment]
One thing you can check is if you telnet localhost on port 57864 (when MIDI2LR is not running), and make sure that the plugin is actually sending all the values.

```
telnet localhost 57864
```

**Comment by thegouger** [comment]
Actually one other thing I realized -
The issue might lie here:
https://github.com/thegouger/MIDI2LR/blob/master/Source/LRPlugin/MIDI2LR.lrdevplugin/MIDI2LR_Client.lua#L123

If you try removing this break statement (and reload the plugin or restart LR), does this resolve the issue?

**Comment by alexlinno** [comment]
Brilliant it works!
Sending only one command when a slider moves in LR with the latest value is only an cosmetic improvement no big deal. Will be using it this week and let you know when problems arise.

**Comment by thegouger** [comment]
I believe motorized faders should work fully now since I fixed the issue with not checking all the parameters here 2ad858e12f457bb8e567add7f490129ddf592cc1

This change is in the latest release, so I will close this issue.

**Comment by clearminds** [comment]
After the last release motors do not move at all - buttons work though.

**Comment by alexlinno** [comment]
works fine for me.Is the MDI2LR still running...ok must be since buttons work....I guess you tried restarting everything....

**Comment by thegouger** [comment]
@clearminds the only change I made was in the plugin (just making sure that when it is notified of a parameter change, it scans all the parameters). You may need to remove/re-add the plugin and/or restart Lightroom and restart MIDI2LR (make sure MIDI2LR is closed first before removing/re-adding the plugin or restarting Lightroom).

**Comment by clearminds** [comment]
@thegouger After I closed down - removed all files and added it a new time and also added it brand new in LR it worked.
