### ISSUE TITLE
Config file extension

### ISSUE THREAD

**Issue by Flowersoft** [thegouger/MIDI2LR#23]
A suggestion, idea:

The Extension of  the configuration file could say '.m2Lr' .
This is a unique and filterable.

**Comment by thegouger** [comment]
Good idea

**Comment by rsjaffe** [comment]
I kind of like it being xml. Then it's easier to open up in an xml-aware editor.

**Comment by pjparra** [comment]
+1, I don't see the point of a custom extension. If it's an xml file, why not simply name it this way.

**Comment by thegouger** [comment]
Closing this as xml is a useful extension (allows people to easily use external editors to edit profiles)
