### ISSUE TITLE
Config file bug

### ISSUE THREAD

**Issue by Flowersoft** [thegouger/MIDI2LR#24]
if you give new functions to the program, the saved settings are loaded back bad value. Not backward compatibile. (Number order.)

**Comment by thegouger** [comment]
Yea, I am planning on using the string representations instead of the array index (especially because it makes a few other things much easier)

**Comment by thegouger** [comment]
Fixed here: 9808ccd3e27b2b18af57c8fcbebddb1c1d84d668
Will take effect after saving profiles with v0.4.1+
