### ISSUE TITLE
Possibly minor bug - Loupe function doesn't seem to do anything

### ISSUE THREAD

**Issue by micksh6** [thegouger/MIDI2LR#26]
Korg NanoKontrol2, latest Lightroom CC x64 (updated today, was the same before), Windows 8.1 x64.

I mapped Tools\Loupe to Marker\Set button and then "S" button to the left of first fader - it doesn't do anything regardless mouse cursor position in Lightroom.
Or, maybe I don't know what it's supposed to do. Other button mappings seem to work well.

**Comment by thegouger** [comment]
The 'loupe' command will explicitly go back to the loupe "tool". It effectively does the same thing as toggling a tool (eg: pressing a button mapped to 'Crop Overlay' twice or hitting R twice will go back to 'loupe'). Admittedly it's not strictly necessary, it's more just there for convenience (so you're not required to hit the same button twice)

**Comment by micksh6** [comment]
Thank you, got it. The loupe command doesn't do anything unless you are in crop, spot removal or other modes. Then Loupe will exit these modes.
Works as designed. Closing the issue.
