### ISSUE TITLE
Support for Numark DJ2Go

### ISSUE THREAD

**Issue by emersonik** [thegouger/MIDI2LR#3]
When I open MIDI2LR it says "Connect to LR", but the controller isn't recognized.
When I open VirtualDJ the controller is recognized and works normally.

**Comment by thegouger** [comment]
MIDI2LR should work with anything that is capable of sending CC messages - which according to the Numark docs the DJ2Go does - https://www.klangfarbe.com/pdf/T//A-T40122_2.pdf.

You'll have to close any other applications using it (eg: VirtualDJ, Ableton Live, etc.). If you connect it after starting MIDI2LR, you'll need to use the 're-scan' button in order for MIDI2LR to pick up events from it.

**Comment by emersonik** [comment]
My bad. I realized that I have to move the sliders in order to make them appear in MIDI2LR.
Sorry.

**Comment by thegouger** [comment]
Ah, no worries. I was thinking about adding a label in the app anyways to indicate this.
