### ISSUE TITLE
Some buttons on BCF2000 not possible to map

### ISSUE THREAD

**Issue by alexlinno** [thegouger/MIDI2LR#34]
When I have a long mapping list, longer then the GUI, and you can scroll it some mapping are reset to 'unmapped'
on the BCF2000 ch4 ctrl 1 mapping to e.g. UNDO works. Itstays mapped even when scrolled  out/in of the list view
however the same action on channel 5 ctrl 1 or chan 1 ctrl 122 causes the mapping to be reset to 'unmapped'. It doesn't matter whether the mapping is on top of the bottom of the list

**Comment by clearminds** [comment]
I experience the same issue here

**Comment by JaimeTak** [comment]
I have the same problem with the nanokontrol

**Comment by Henk72** [comment]
Thanks for the great application

I have the same issue on the BehringerBCF2000. If you map some more buttons, some others are remapped. This happens if you map the rotary encoders at the top with the 4 different modes in the preset (4 buttons on the op right allow to change it)

**Comment by thegouger** [comment]
Fixed this here: 646d21801b792c16749d31b660ed6205bac03087
This will be fixed in v0.4.0 (which I will be releasing shortly)
