### ISSUE TITLE
Remembering save location for settings

### ISSUE THREAD

**Issue by rsjaffe** [thegouger/MIDI2LR#35]
It would be nice to be able to specify the default directory location for settings. Currently, the dialog box opens with the same location each time (the Adobe application directory). 

The solution could be one of three:
* Add an option to set the default location
* Remember, when opening up the file dialog, which location was last used
* Combine the two--Use the default location when app started, remember last used while app is running.

Thanks

Rory

**Comment by thegouger** [comment]
Yup - currently working on a 'Profile Manager' (to allow the user to switch between profiles using buttons), which will allow the user to set a directory for the profiles

**Comment by thegouger** [comment]
This was added here: eee0d5042cc179d6c246b617789546b9878962be and is available in the latest release

I'll be improving the profile system to make it a bit more user friendly though
