### ISSUE TITLE
If slider set to "0", will not update when next picture selected

### ISSUE THREAD

**Issue by rsjaffe** [thegouger/MIDI2LR#38]
To replicate, in Develop view, move highlights slider on BFC2000 to minimum (0) and another slider to an arbitrary setting. Then move to next picture (using Lightroom). Highlights slider stays at 0 even if that is not correct in picture, other slider adjusts appropriately. Highlight slider starts working once you move it within pickup range of picture's setting.

Is the compare to 0 the problem?:
```c++
void LR_IPC_OUT::handleMidiCC(int midiChannel, int controller, int value)
{
    MIDI_Message cc(midiChannel, controller, true);

    if (!CommandMap::getInstance().messageExistsInMap(cc) || 
         CommandMap::getInstance().getCommandforMessage(cc) == 0 ||
         CommandMap::getInstance().getCommandforMessage(cc) >= LRCommandList::LRStringList.size())
        return;

    _commandToSend = LRCommandList::LRStringList[(int)CommandMap::getInstance().getCommandforMessage(cc)];
    _valueToSend = value;
    handleAsyncUpdate();
}
```

**Comment by thegouger** [comment]
I suppose I should use a constant for that, but basically that 0 is just used for the 'Unmapped' state.

Are you saying that the slider won't update to the correct position on the BCF2000 (ie the motorized slider doesn't move when you switch photos)?

**Comment by rsjaffe** [comment]
Yes

**Comment by thegouger** [comment]
Noted. I will debug this.

**Comment by rsjaffe** [comment]
Additional observation. In lightroom, set Brightness to -100 on a picture. Go to another picture with brightness of 0 and move brightness slider on BCF2000 to 0. In lightroom, go back to the picture with Brightness -100. Slider on BCF2000 remains at 0.

**Comment by rsjaffe** [comment]
Oops--meant highlights, not brightness.

**Comment by rsjaffe** [comment]
Wait a minute. I just noticed a second control ("40") was also mapped to brightness. That was a button control. Removed that, and it wasn't fixed. BUT, reboot, come back into app, everything is working fine. Don't know if I'd call this a bug any more--more like an unexpected side effect of mapping both a slider and a button to a function that should take a slider.

Sorry

**Comment by thegouger** [comment]
Ah, actually my plan is to disallow people mapping the same command to multiple sliders/knobs (unless there is truly a good use case for it).
