### ISSUE TITLE
Ranking and Flags

### ISSUE THREAD

**Issue by edm81363** [thegouger/MIDI2LR#5]
Hi -

LOVE this program - thanks a ton!

I could really benefit from two functions in particular - 3 stars and 0 stars. But it wouldn't make sense to implement them alone. I suggest adding to the Photo Actions section, or adding a Rating / Sorting category that provides;

0 Star (I think this may be called "Reset Rating" inside LR)
1 Star
2 Star
3 Star
4 Star
5 Star
Set Label Red
Set Label Yellow
Set Label Green
Set Label Blue

I know that you recently added Remove Flag, but I propose that Toggle Flag might be more useful.

I hope this information is helpful - keep up the great work, it is much appreciated.

**Comment by edm81363** [comment]
Thanks for the Set Rating to 0 - very useful!

**Comment by edm81363** [comment]
Would still like to see;

Set Rating to 1
Set Rating to 2
Set Rating to 3
Set Rating to 4
Set Rating to 5

**Comment by thegouger** [comment]
Sure, I'll tackle this next

**Comment by thegouger** [comment]
Added here: bb1f570e5325295cd44670f39f9560e2386d1d08
