### ISSUE TITLE
Version 0.4.1 doesn't send values back to controller

### ISSUE THREAD

**Issue by rsjaffe** [thegouger/MIDI2LR#50]
I'm not seeing any movement in the motorized faders. Sending data to LR from the MIDI control surface works normally. Did the change to using the string for the command map instead of the number break something?

**Comment by thegouger** [comment]
Did you try removing/re-adding the plugin / restarting LR? I checked and it is sending the values to MIDI out devices. You can also check to make sure you can connect to the port 58764 when MIDI2LR isn't running (eg try to telnet to localhost 58764).

On another note, my BCF2000 is in the mail, so I'll actually be able to debug these issues better.

**Comment by wockawocka** [comment]
rsjaffe, I get that too in most versions but I simply close the Midi2lr box down (not the actual plugin, then restart lightroom.

I also ensure ligthroom is in develop mode when I do this and it wakes things up again.

**Comment by wockawocka** [comment]
Nice update btw, at this pace V1.0 will be able to send people to Mars.

**Comment by thegouger** [comment]
It's weird - it doesn't happen to me very often (and I replace the plugin a lot when testing). But I'm sure it has something to do with LR not closing the sender socket properly. I'll see what I can do to reproduce it more often, and see how to remedy it.

**Comment by rsjaffe** [comment]
I rebooted and everything is working fine! Sorry for the false alarm.
