### ISSUE TITLE
Handling NRPN messages

### ISSUE THREAD

**Issue by rsjaffe** [thegouger/MIDI2LR#55]
Probably the safest way to implement wider range CC values is to use NRPN MIDI messages. Behringer has another method that uses standard CC messages, but I worry that that is error-prone.

Looks like the one method that would need to be changed on the input side is MainContentComponent::handleMidiCC, which currently assumes that each CC message is a normal one. We could have it shift into NRPN mode if the CC channel is 98, look for the second channel value message at channel 99, then values at 96/97 or 6/38. See https://github.com/kunitoki/juced/blob/master/juce/src/extended/dependancies/dssi-1.0.0/doc/midi-controllers.txt for details about tne NRPN message format.

I may give this a try later this weekend if I have time.

**Comment by rsjaffe** [comment]
And we could stage the nrpn messages as they come in through the following structure:
typedef std::tuple<int,int,int>  NRPNcomponents;
typedef std::pair<int,int> NRPNChannelControl
std::unordered_map<NRPNChannelControl, NRPNcomponents> NRPNstaging;

Where the pair would be channel and control numbers, and components would be message number (1-4), channel storage, control storage.

**Comment by thegouger** [comment]
This is a pretty good idea. Regretfully I won't have time in the foreseeable future to continue developing MIDI2LR.
If you or anybody else would like to continue, we can discuss over email midi2lr@gmail.com.

**Comment by rsjaffe** [comment]
This issue was moved to rsjaffe/MIDI2LR#1

**Comment by rsjaffe** [comment]
Could you send me the latest Mac version? I didn't save a copy and now
there are requests for it. The first build I will do won't be until the end
of this month. Thanks.

**Comment by thegouger** [comment]
Sure, the latest release is available for download here:
https://github.com/thegouger/MIDI2LR/releases/tag/v0.4.1
