### ISSUE TITLE
Next / Previous not working

### ISSUE THREAD

**Issue by edm81363** [thegouger/MIDI2LR#6]
Hi -

When I assign and press the Next Photo and Previous Photo button, they do not work. This behavior is observed in Full Screen mode and is reproducible. 

Further, if the button is pressed from Grid View, then LR changes to the Develop module.

The desired behavior would be for Lightroom to move one image forward or backward.

Also, when Next Photo is assigned to a button, the mapping is shown as "Next" when "Next Photo" might be more informative. (Same for previous.)

**Comment by thegouger** [comment]
Can you check that you're using the updated plugin as well? Note that you might need to close MIDI2LR, remove the plugin in Lightroom, and then re-add it. I'll make an actual release with instructions once I build it on my Mac VM.

**Comment by edm81363** [comment]
I was compiling the build in Xcode without removing and readding the plugin in LR.
