### ISSUE TITLE
Reset individual parameters

### ISSUE THREAD

**Issue by edm81363** [thegouger/MIDI2LR#8]
I would love to have the ability to reset individual parameters. Then I could map Fader 1 to Exposure, and R button 1 to reset Exposure.

**Comment by edm81363** [comment]
I think this can be accomplished using;

LrDevelopController.resetToDefault( param )

http://lightroomsolutions.com/sdk/modules/LrDevelopController.html

**Comment by thegouger** [comment]
Good idea, I'll look into this

**Comment by thegouger** [comment]
I added a command to reset the last adjusted parameter here 858a22886992b53e0c2ab8de1782385686bc3a04

If there's more demand for resetting specific parameters, I can add that in later as well.
